name: Docker Test

on: [push]

jobs:
  build:
    name: TryUbuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Docker build
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: try ls
        run: ls $GITHUB_WORKSPACE
      - name: do docker build
        run: docker build --squash -f Dockerfile-python-sims $GITHUB_WORKSPACE/jupyter
       
