name: Docker Test

on: [push]

jobs:
  build:
    name: TryUbuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username heather999 --password-stdin
      - name: checkout dockerfiles 
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: try ls
        run: ls $GITHUB_WORKSPACE
      - name: do docker build
        run: docker build -t heather999/juptyer-test:latest -f $GITHUB_WORKSPACE/jupyter/Dockerfile-python-sims . 
      - name: Docker push
        run: docker push heather999/jupyter-test:latest
       
